# Generated by Django 5.1.15 on 2025-12-25 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя класса')),
                ('students', models.ManyToManyField(blank=True, related_name='classes_as_student', to=settings.AUTH_USER_MODEL, verbose_name='Ученики')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_as_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_1', models.PositiveIntegerField(default=0, verbose_name='Порог для 1')),
                ('threshold_2', models.PositiveIntegerField(default=30, verbose_name='Порог для 2')),
                ('threshold_3', models.PositiveIntegerField(default=51, verbose_name='Порог для 3')),
                ('threshold_4', models.PositiveIntegerField(default=71, verbose_name='Порог для 4')),
                ('threshold_5', models.PositiveIntegerField(default=89, verbose_name='Порог для 4')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Тема задания')),
                ('description', models.TextField(verbose_name='Комментарий к заданию')),
                ('homework_file', models.FileField(blank=True, null=True, upload_to='homeworks/', verbose_name='Файл с заданием')),
                ('questions', models.JSONField(verbose_name='Структура вопросов')),
                ('correct_answers', models.JSONField(verbose_name='Правильные ответы')),
                ('assigned_date', models.DateField(verbose_name='Дата выдачи')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('max_score', models.PositiveIntegerField(default=0, verbose_name='Максимальный балл')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='homework.classroom', verbose_name='Класс')),
                ('grade_scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homeworks', to='homework.gradescale', verbose_name='Шкала оценивания')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(verbose_name='Ответы ученика')),
                ('auto_score', models.PositiveIntegerField(default=0, verbose_name='Балл после проверки системы')),
                ('final_score', models.PositiveIntegerField(default=0, verbose_name='Итоговый балл')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('graded', models.BooleanField(default=False, verbose_name='Проверено')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий учителя')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('homework_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homeworktemplate', verbose_name='Домашнее задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
        ),
    ]
