# Generated by Django 5.1.15 on 2025-12-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_alter_gradescale_threshold_5_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='gradescale',
            options={'verbose_name': 'Шкала оценивания', 'verbose_name_plural': 'Шкалы оценивания'},
        ),
        migrations.AlterModelOptions(
            name='homeworktemplate',
            options={'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='studentsubmission',
            options={'verbose_name': 'Ответ ученика', 'verbose_name_plural': 'Ответы учеников'},
        ),
    ]
