# Generated by Django 5.1.15 on 2026-01-19 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_alter_classroom_students_alter_classroom_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_profiles', to='homework.classroom'),
        ),
    ]
