# Generated by Django 5.1.15 on 2026-01-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_profile_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
    ]
