# Generated by Django 5.1.15 on 2026-01-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_remove_classroom_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gradescale',
            name='teacher',
        ),
    ]
